---
title: "R Notebook"
output: html_document
---
```{r}
runrec <- read.table('record_mod.txt', header=T)
n <- dim(runrec)[1]
p <- dim(runrec)[2]
runrec
```
```{r}
# we make the units of measure homogeneous across the variables -> transform all measures in seconds
runrec[,4:7] <- runrec[,4:7]*60
runrec
```

Type any R code in the chunk, for example:
```{r}
# Let's plot the distribution of teh records based on the category
boxplot(runrec)
#lloking at the graph we see that the variability increases with the increase in distance of the competition. In particular is extrimely well visible how variability of Marathon is much higher compared to all the others
```
```{r}
#Plot the same boxplot as before but with the log to reduce variability of categories and see the new distributions
boxplot(log(runrec)) #done by me
```
```{r}
#PCA
pc.runrec <- princomp(runrec, scores=T)
summary(pc.runrec)
#The first Component is explaining all the variability (no good)
```
```{r}
#Let's plot the loadings of the first 7 principal components
load.rec <- pc.runrec$loadings
par(mar = c(1,4,0,2), mfrow = c(7,1))
for(i in 1:7) barplot(load.rec[,i], ylim = c(-1, 1))
```
```{r}
layout(matrix(c(2,3,1,3),2,byrow=T))
# by plotting the output of the princomp command you directly plot the variance explained
plot(pc.runrec, main='Principal components', ylim=c(0,3.5e6))
barplot(sapply(runrec,sd)^2, main='Original Variables', ylim=c(0,3.5e6), ylab='Variances')
plot(cumsum(pc.runrec$sd^2)/sum(pc.runrec$sd^2), type='b', axes=F, xlab='number of components',
     ylab='contribution to the total variance', ylim=c(0,1))
abline(h=1, col='blue')
abline(h=0.8, lty=2, col='blue')
axis(2,at=0:10/10,labels=0:10/10)
axis(1,at=1:ncol(runrec),labels=1:ncol(runrec),las=2)

# The first PC (var. Marathon) explains more than 99.98% of the total variability. This is due to the masking effect of that variable over the others. In fact values and variability of this variable are stronngly different compared to others
```
```{r}
# Let's compare boxplots of the scores and the original variables

layout(matrix(c(1,2),2))
boxplot(runrec, las=2, col='red', main='Original variables')
scores.runrec <- pc.runrec$scores
scores.runrec <- data.frame(scores.runrec)
boxplot(scores.runrec, las=2, col='red', main='Principal components')
# As we were expecting, the variance along the 1st component is bigger the variance along the others
```
```{r}
# Now we use a biplot to plot the first two principal component and the respective loadings in red.
biplot(pc.runrec, scale=0, cex=.55)#,xlim=c(-10000,10000))

```
## Standardization
```{r}
#Since the PCA did not explained so much about data (the variables have ranges and avriability whih are too different) we are going to try to standardize the values
runrec.sd <- scale(runrec)
runrec.sd <- data.frame(runrec.sd)
runrec.sd
```
```{r}
pc.runrec <- princomp(runrec.sd, scores=T)
pc.runrec
summary(pc.runrec)
```
```{r}
#Check the explained variance by the variables
layout(matrix(c(2,3,1,3),2,byrow=T))
plot(pc.runrec, las=2, main='Principal Components', ylim=c(0,6))
abline(h=1, col='blue')
barplot(sapply(runrec.sd,sd)^2, las=2, main='Original Variables', ylim=c(0,6), ylab='Variances')
plot(cumsum(pc.runrec$sde^2)/sum(pc.runrec$sde^2), type='b', axes=F, xlab='Number of Components', ylab='Effect on Total Variance', ylim=c(0,1))
axis(2,at=0:10/10,labels=0:10/10)
axis(1,at=1:ncol(runrec.sd),labels=1:ncol(runrec.sd),las=2)
#Looking at the representatiosn below, if we wanted to perform dimensionality reduction, we could keep 1 or 2 PCs
```
```{r}
#Given that the first 2 components explain most of the variability, let's now plot the loading of te first 2 components
load.rec <- pc.runrec$loadings

par(mar = c(2,2,2,1), mfrow=c(2,1))
for(i in 1:2)barplot(load.rec[,i], ylim = c(-1, 1), main=paste('Loadings PC ',i,sep=''))
```
```{r}
# Interpretation of the loadings:
# In this case, the first PC represents an average of the times of all the disciplines, taken with very similar weights.
# The second PC contrasts the short distances (m100, m200, m400) with the long distances (m800, m1500, m3000, Marathon)
```
```{r}
#Focusing on the first 2 PC we have that
# High PC1: long times in all the disciplines
# Low PC1: short times in all the disciplines
# High PC2: long times in short distances, short times in long distances
# Low PC2: short times in short distances, long times in long distances

```
```{r}
layout(matrix(c(1,2),2))
boxplot(runrec.sd, las=2, col='red', main='Original variables')
scores.runrec <- pc.runrec$scores
scores.runrec <- data.frame(scores.runrec)
boxplot(scores.runrec, las=2, col='red', main='Principal components')

```
```{r}
biplot(pc.runrec)
```
